Feature('shopping');

Scenario('successful purchase', ({ I }) => {

    I.amOnPage('https://automationpratice.com.br/')
    I.click('//*[@class="fa fa-shopping-bag"]')
    I.click('//*[@class="offcanvas-wishlist-item-delete"]')
    I.click('//*[@class="offcanvas-wishlist-item-delete"]')
    I.click('//*[@class="offcanvas-wishlist-item-delete"]')
    I.click('//*[@id="offcanvas-add-cart"]/div[1]/button')
    I.click('Shop')
    I.click('Shop Four Grid')
    I.click('//*[@id="shop_main_area"]/div/div[2]/div[2]/div/div[1]/a/img[2]')
    I.click('Add To Cart')
    I.click('Shop')
    I.click('Shop Four Grid')
    I.click('//*[@class="hover-image"]')
    I.click('//*[@class="theme-btn-one btn-black-overlay btn_sm"]')
    I.click('//*[@class="fa fa-shopping-bag"]')
    I.click('//*[@class="theme-btn-one btn-black-overlay btn_md"]')
    I.click('//*[@id="cart_area_one"]/div/div/div[3]/div/div/div[4]/a')
    I.fillField('#fname', 'ANA')
    I.fillField('#lname', 'MORAIS')
    I.fillField('#cname', 'NAÇÕES UNIDAS')
    I.fillField('#email', 'ana.nacoesunidas@gmail.com')
    I.click('#country')
    I.selectOption('#country', 'Afghanistan')
    I.click('#city')
    I.selectOption('#city', 'Aland Islands')
    I.fillField('#zip', ('780309'))
    I.click('#faddress')
    I.fillField('#faddress', '720 Michigan Avenue, Chicago, IL – 60605, United States')
    I.click('#messages')
    I.fillField('#messages', 'When delivering, request the signature of the person responsible.')
    I.click('#materialUnchecked')
    I.click('Save')
    I.click('Mobile Banking')
    I.click('Place Order')

});
